data:
  in_memory: 1
  num_workers: 24
dist:
  world_size: 8
logging:
  folder: /workspace/log
  save_model_freq: 4
  log_level: 2
lr:
  lr: 0.5
  lr_schedule_type: cyclic
model:
  arch: alexnet_5layers
resolution:
  end_ramp: 27
  max_res: 192
  min_res: 160
  start_ramp: 23
training:
  batch_size: 4096
  bn_wd: 0
  distributed: 1
  epochs: 32
  label_smoothing: 0.1
  momentum: 0.9
  optimizer: sgd
  weight_decay: 5e-5
  use_blurpool: 1
  alexnet_topk: 0.2
validation:
  lr_tta: true
  resolution: 256
