data:
  in_memory: 1
  num_workers: 24
dist:
  world_size: 2
logging:
  folder: /workspace/log
  save_model_freq: 50
  log_level: 2
lr:
  lr: 0.1
  lr_schedule_type: cosine
model:
  arch: alexnet_5layers
resolution:
  end_ramp: 27
  max_res: 224
  min_res: 224
  start_ramp: 23
training:
  batch_size: 2048
  bn_wd: 0
  distributed: 1
  epochs: 90
  label_smoothing: 0
  momentum: 0.9
  optimizer: sgd
  weight_decay: 5e-5
  use_blurpool: 0
  alexnet_topk: 0.05
  topk_tau: 0.6
  eval_only: 1
validation:
  lr_tta: true
  resolution: 256
resume:
  model_ckpt: /home/ylz1122/ffcv-imagenet-train/scripts/alexnet/train_results/alexnet_configs/alexnet_5layers_train_topk_tau/e42da2c2-2470-4b77-9f25-d0fe183aa749/weights_ep_89.pt
  resume_model_from_ckpt: 1
  init_eval_checker: 1
