data:
  in_memory: 1
  num_workers: 24
dist:
  world_size: 2
logging:
  folder: /workspace/log
  save_model_freq: 50
  log_level: 2
lr:
  lr: 0.1
  lr_schedule_type: cosine
model:
  arch: alexnet_2layer
resolution:
  end_ramp: 27
  max_res: 224
  min_res: 224
  start_ramp: 23
training:
  batch_size: 512
  bn_wd: 0
  distributed: 1
  epochs: 90
  label_smoothing: 0
  momentum: 0.9
  optimizer: sgd
  weight_decay: 5e-5
  use_blurpool: 0
  alexnet_topk: 0.2
  topk_tau: 0.
validation:
  lr_tta: true
  resolution: 256
