data:
  in_memory: 1
  num_workers: 20
dist:
  world_size: 2
logging:
  folder: /workspace/log
  log_level: 2
  save_model_freq: 5
lr:
  lr: 0.01
  lr_schedule_type: cyclic
model:
  arch: alexnet_5layers
resolution:
  end_ramp: 27
  max_res: 192
  min_res: 160
  start_ramp: 23
training:
  batch_size: 2048
  bn_wd: 0
  distributed: 1
  epochs: 90
  label_smoothing: 0.1
  momentum: 0.9
  optimizer: sgd
  weight_decay: 0.0001
  use_blurpool: 1
  alexnet_topk: 0.2
  l1_sparsity_lamda: 0.
validation:
  lr_tta: true
  resolution: 256
