data:
  in_memory: 1
  num_workers: 20
dist:
  world_size: 2
logging:
  folder: /workspace/log
  log_level: 2
  save_model_freq: 5
lr:
  lr: 0.01
  lr_schedule_type: cyclic
model:
  # arch: alexnet_5layers_finetune  
  arch: alexnet_2layer_finetune
resolution:
  end_ramp: 27
  max_res: 224
  min_res: 224
  start_ramp: 23
training:
  batch_size: 2048
  bn_wd: 0
  distributed: 1
  epochs: 90
  label_smoothing: 0.1
  momentum: 0.9
  optimizer: sgd
  weight_decay: 5e-5
  use_blurpool: 0
  alexnet_topk: 0.2
validation:
  lr_tta: true
  resolution: 256
resume:
  init_eval_checker: 1
  # model_ckpt: /home/ylz1122/ffcv-imagenet-train/scripts/alexnet/train_results/alexnet_configs/alexnet_5layers_32_epochs_test_finetune_alex-original/3937dfee-fc55-4c8d-adcf-d8137c5bbe22/weights_ep_89.pt
  # optim_ckpt: /home/ylz1122/ffcv-imagenet-train/scripts/alexnet/train_results/alexnet_configs/alexnet_5layers_32_epochs_test_finetune_alex-original/3937dfee-fc55-4c8d-adcf-d8137c5bbe22/weights_ep_89_optimizer.pt
  resume_opt_from_ckpt: 0
  resume_model_from_ckpt: 0