data:
  gpu: 0
  in_memory: 1
  num_workers: 12
dist:
  world_size: 1
logging:
  folder: /tmp/
  save_model_freq: 1
lr:
  lr: 0.5
  lr_schedule_type: cyclic
model:
  arch: ViT+B_16_imagenet1k
resolution:
  end_ramp: 20
  max_res: 224
  min_res: 224
  start_ramp: 17
training:
  batch_size: 256
  bn_wd: 0
  distributed: 1
  epochs: 24
  label_smoothing: 0.1
  momentum: 0.9
  optimizer: sgd
  weight_decay: 0.0001
  use_blurpool: 1
validation:
  lr_tta: true
  resolution: 224
