data:
  in_memory: 1
  num_workers: 24
dist:
  world_size: 8
logging:
  folder: /workspace/log
  save_model_freq: 1
lr:
  lr: 0.1
  lr_schedule_type: cyclic
model:
  arch: ViT+B_16_imagenet1k
resolution:
  end_ramp: 27
  max_res: 192
  min_res: 32
  start_ramp: 1
training:
  batch_size: 400
  bn_wd: 0
  distributed: 1
  epochs: 32
  label_smoothing: 0.1
  momentum: 0.9
  optimizer: sgd
  weight_decay: 0.0001
  use_blurpool: 1
validation:
  lr_tta: true
  resolution: 256
  batch_size: 40
resume:
  optim_ckpt: ""
  resume_opt_from_ckpt: 0
  model_ckpt: ""
  resume_model_from_ckpt: 0
  init_eval_checker: 0
