data:
  in_memory: 1
  num_workers: 12
dist:
  world_size: 2
logging:
  folder: /tmp/
lr:
  lr: 1.7
  lr_schedule_type: cyclic
model:
  arch: resnet50_4layers
resolution:
  end_ramp: 27
  max_res: 192
  min_res: 160
  start_ramp: 23
training:
  batch_size: 512
  bn_wd: 0
  distributed: 1
  epochs: 32
  label_smoothing: 0.1
  momentum: 0.9
  optimizer: sgd
  weight_decay: 0.0001
  use_blurpool: 1
  resnet50_topk: 0.2
validation:
  lr_tta: true
  resolution: 256
