data:
  in_memory: 1
  num_workers: 12
dist:
  world_size: 8
logging:
  folder: /workspace/log
  log_level: 2
  save_model_freq: 4
lr:
  lr: 0.002
  lr_schedule_type: cosine
model:
  arch: ViT+S
resolution:
  end_ramp: 27
  max_res: 224
  min_res: 192
  start_ramp: 1
training:
  batch_size: 512
  bn_wd: 0
  distributed: 1
  epochs: 100
  label_smoothing: 0.1
  momentum: 0.9
  optimizer: sgd
  weight_decay: 0.0001
  use_blurpool: 1
  resnet50_topk: 1.
validation:
  lr_tta: true
  resolution: 256
  batch_size: 40
